# Generated by Django 6.0.1 on 2026-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='display_input',
            field=models.TextField(blank=True, help_text='Human-readable version of the input (shown to users)'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='display_output',
            field=models.TextField(blank=True, help_text='Human-readable version of the output (shown to users)'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional explanation for this example'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(help_text='Exact stdout expected from the program'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(help_text="Raw stdin passed to the user's program"),
        ),
    ]
