# Generated by Django 6.0.1 on 2026-01-31 02:33

from django.db import migrations, models
from django.template.defaultfilters import slugify


def populate_slugs(apps, schema_editor):
    """Generate slugs for existing problems."""
    Problem = apps.get_model('problems', 'Problem')
    for problem in Problem.objects.all():
        if not problem.slug:
            problem.slug = slugify(problem.title)
            problem.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    """Clear slugs (reverse operation)."""
    Problem = apps.get_model('problems', 'Problem')
    Problem.objects.update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_testcase_display_input_testcase_display_output_and_more'),
    ]

    operations = [
        # Step 1: Add the field as a plain CharField without indexes
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.CharField(max_length=120, default=''),
        ),
        # Step 2: Populate slugs for existing records
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        # Step 3: Convert to SlugField with unique constraint and proper indexing
        migrations.AlterField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
