# Generated by Django 6.0.1 on 2026-01-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_add_slug_to_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='entrypoint_name',
            field=models.CharField(blank=True, help_text="For function-call mode: function/method name to call (e.g., 'twoSum')", max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='entrypoint_type',
            field=models.CharField(blank=True, choices=[('function', 'Bare Function'), ('class', 'Solution Class')], default='class', help_text='For function-call mode: what the user implements', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='judge_mode',
            field=models.CharField(choices=[('stdin', 'Standard I/O'), ('function', 'Function Call (LeetCode-style)')], default='stdin', help_text='How submissions are executed and evaluated', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='signature_text',
            field=models.CharField(blank=True, help_text="Display signature shown to users (e.g., 'def twoSum(nums: list[int], target: int) -> list[int]')", max_length=500),
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Template code pre-filled in the editor for users'),
        ),
    ]
