# Generated by Django

from django.db import migrations
import json


def add_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    TestCase = apps.get_model('problems', 'TestCase')
    
    # Problem 1: Reverse Integer
    reverse_int = Problem.objects.create(
        title="Reverse Integer",
        slug="reverse-integer",
        description="""Given a signed 32-bit integer x, return x with its digits reversed.

If reversing x causes the value to go outside the signed 32-bit integer range [-2^31, 2^31 - 1], then return 0.

Assume the environment does not allow you to store 64-bit integers (signed or unsigned).""",
        constraints="""- -2^31 <= x <= 2^31 - 1""",
        follow_up="",
        difficulty=1,  # Easy
        judge_mode='function',
        entrypoint_type='class',
        entrypoint_name='reverse',
        signature_text='def reverse(self, x: int) -> int',
        starter_code='''class Solution:
    def reverse(self, x: int) -> int:
        # Your code here
        pass''',
        is_published=True
    )
    
    # Test cases for Reverse Integer
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": 123}',
        expected_output='321',
        display_input='x = 123',
        display_output='321',
        explanation='',
        is_sample=True
    )
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": -123}',
        expected_output='-321',
        display_input='x = -123',
        display_output='-321',
        explanation='',
        is_sample=True
    )
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": 120}',
        expected_output='21',
        display_input='x = 120',
        display_output='21',
        explanation='Trailing zeros are removed.',
        is_sample=True
    )
    # Hidden test cases
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": 0}',
        expected_output='0',
        is_sample=False
    )
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": 1534236469}',
        expected_output='0',
        is_sample=False
    )
    TestCase.objects.create(
        problem=reverse_int,
        input_data='{"x": -2147483648}',
        expected_output='0',
        is_sample=False
    )
    
    # Problem 2: Roman to Integer
    roman_int = Problem.objects.create(
        title="Roman to Integer",
        slug="roman-to-integer",
        description="""Roman numerals are represented by seven different symbols: I, V, X, L, C, D and M.

Symbol       Value
I             1
V             5
X             10
L             50
C             100
D             500
M             1000

For example, 2 is written as II in Roman numeral, just two ones added together. 12 is written as XII, which is simply X + II. The number 27 is written as XXVII, which is XX + V + II.

Roman numerals are usually written largest to smallest from left to right. However, the numeral for four is not IIII. Instead, the number four is written as IV. Because the one is before the five we subtract it making four. The same principle applies to the number nine, which is written as IX.

There are six instances where subtraction is used:
- I can be placed before V (5) and X (10) to make 4 and 9. 
- X can be placed before L (50) and C (100) to make 40 and 90. 
- C can be placed before D (500) and M (1000) to make 400 and 900.

Given a roman numeral, convert it to an integer.""",
        constraints="""- 1 <= s.length <= 15
- s contains only the characters ('I', 'V', 'X', 'L', 'C', 'D', 'M')
- It is guaranteed that s is a valid roman numeral in the range [1, 3999]""",
        follow_up="",
        difficulty=1,  # Easy
        judge_mode='function',
        entrypoint_type='class',
        entrypoint_name='romanToInt',
        signature_text='def romanToInt(self, s: str) -> int',
        starter_code='''class Solution:
    def romanToInt(self, s: str) -> int:
        # Your code here
        pass''',
        is_published=True
    )
    
    # Test cases for Roman to Integer
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "III"}',
        expected_output='3',
        display_input='s = "III"',
        display_output='3',
        explanation='III = 3',
        is_sample=True
    )
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "LVIII"}',
        expected_output='58',
        display_input='s = "LVIII"',
        display_output='58',
        explanation='L = 50, V = 5, III = 3',
        is_sample=True
    )
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "MCMXCIV"}',
        expected_output='1994',
        display_input='s = "MCMXCIV"',
        display_output='1994',
        explanation='M = 1000, CM = 900, XC = 90, IV = 4',
        is_sample=True
    )
    # Hidden test cases
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "IV"}',
        expected_output='4',
        is_sample=False
    )
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "IX"}',
        expected_output='9',
        is_sample=False
    )
    TestCase.objects.create(
        problem=roman_int,
        input_data='{"s": "MMMCMXCIX"}',
        expected_output='3999',
        is_sample=False
    )
    
    # Problem 3: FizzBuzz (stdin/stdout mode for variety)
    fizzbuzz = Problem.objects.create(
        title="FizzBuzz",
        slug="fizzbuzz",
        description="""Given an integer n, print numbers from 1 to n, but:
- For multiples of 3, print "Fizz" instead of the number
- For multiples of 5, print "Buzz" instead of the number
- For multiples of both 3 and 5, print "FizzBuzz" instead of the number

Print each output on a new line.""",
        constraints="""- 1 <= n <= 100""",
        follow_up="Can you solve this without using modulo operator?",
        difficulty=1,  # Easy
        judge_mode='stdin',
        entrypoint_type='',
        entrypoint_name='',
        signature_text='',
        starter_code='',
        is_published=True
    )
    
    # Test cases for FizzBuzz
    TestCase.objects.create(
        problem=fizzbuzz,
        input_data='3',
        expected_output='1\n2\nFizz',
        display_input='n = 3',
        display_output='1\n2\nFizz',
        explanation='',
        is_sample=True
    )
    TestCase.objects.create(
        problem=fizzbuzz,
        input_data='5',
        expected_output='1\n2\nFizz\n4\nBuzz',
        display_input='n = 5',
        display_output='1\n2\nFizz\n4\nBuzz',
        explanation='',
        is_sample=True
    )
    TestCase.objects.create(
        problem=fizzbuzz,
        input_data='15',
        expected_output='1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',
        display_input='n = 15',
        display_output='1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz',
        explanation='15 is divisible by both 3 and 5, so it prints FizzBuzz',
        is_sample=True
    )
    # Hidden test cases
    TestCase.objects.create(
        problem=fizzbuzz,
        input_data='1',
        expected_output='1',
        is_sample=False
    )
    TestCase.objects.create(
        problem=fizzbuzz,
        input_data='30',
        expected_output='1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\nFizz\n22\n23\nFizz\nBuzz\n26\nFizz\n28\n29\nFizzBuzz',
        is_sample=False
    )
    
    # Problem 4: Longest Common Prefix
    lcp = Problem.objects.create(
        title="Longest Common Prefix",
        slug="longest-common-prefix",
        description="""Write a function to find the longest common prefix string amongst an array of strings.

If there is no common prefix, return an empty string "".""",
        constraints="""- 1 <= strs.length <= 200
- 0 <= strs[i].length <= 200
- strs[i] consists of only lowercase English letters""",
        follow_up="",
        difficulty=1,  # Easy
        judge_mode='function',
        entrypoint_type='class',
        entrypoint_name='longestCommonPrefix',
        signature_text='def longestCommonPrefix(self, strs: list[str]) -> str',
        starter_code='''class Solution:
    def longestCommonPrefix(self, strs: list[str]) -> str:
        # Your code here
        pass''',
        is_published=True
    )
    
    # Test cases for Longest Common Prefix
    TestCase.objects.create(
        problem=lcp,
        input_data='{"strs": ["flower", "flow", "flight"]}',
        expected_output='"fl"',
        display_input='strs = ["flower", "flow", "flight"]',
        display_output='"fl"',
        explanation='',
        is_sample=True
    )
    TestCase.objects.create(
        problem=lcp,
        input_data='{"strs": ["dog", "racecar", "car"]}',
        expected_output='""',
        display_input='strs = ["dog", "racecar", "car"]',
        display_output='""',
        explanation='There is no common prefix among the input strings.',
        is_sample=True
    )
    # Hidden test cases
    TestCase.objects.create(
        problem=lcp,
        input_data='{"strs": ["a"]}',
        expected_output='"a"',
        is_sample=False
    )
    TestCase.objects.create(
        problem=lcp,
        input_data='{"strs": ["", "b"]}',
        expected_output='""',
        is_sample=False
    )
    TestCase.objects.create(
        problem=lcp,
        input_data='{"strs": ["abc", "abc", "abc"]}',
        expected_output='"abc"',
        is_sample=False
    )


def remove_problems(apps, schema_editor):
    Problem = apps.get_model('problems', 'Problem')
    Problem.objects.filter(slug__in=[
        'reverse-integer',
        'roman-to-integer',
        'fizzbuzz',
        'longest-common-prefix'
    ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_add_judge_mode'),
    ]

    operations = [
        migrations.RunPython(add_problems, remove_problems),
    ]
