# Generated by Django 6.0.1 on 2026-01-31 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_add_variety_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.TextField(help_text='For stdin mode: exact stdout expected. For function-call mode: JSON value of expected return (e.g., [0,1])'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(help_text='For stdin mode: raw text passed to stdin. For function-call mode: JSON object of arguments (e.g., {"nums": [1,2], "target": 3})'),
        ),
    ]
