from django.db import migrations
from django.template.defaultfilters import slugify
import json


PROBLEM_SLUGS = [
    "valid-parentheses",
    "longest-common-prefix",
    "roman-to-integer",
    "palindrome-number",
    "plus-one",
    "missing-number",
    "single-number",
    "first-unique-character-in-a-string",
    "valid-mountain-array",
    "squares-of-a-sorted-array",
    "running-sum-of-1d-array",
    "richest-customer-wealth",
    "number-of-1-bits",
    "pascals-triangle-ii",
    "transpose-matrix",
    "find-pivot-index",
    "intersection-of-two-arrays",
    "fizz-buzz",
    "valid-sudoku",
    "top-k-frequent-elements",
    "subarray-sum-equals-k",
    "longest-substring-without-repeating-characters",
    "container-with-most-water",
    "longest-palindromic-substring-length",
    "coin-change",
    "house-robber-ii",
    "number-of-islands",
    "course-schedule",
    "search-in-rotated-sorted-array",
    "find-minimum-in-rotated-sorted-array",
    "target-sum-ways",
    "longest-consecutive-sequence",
    "sort-colors",
    "rotate-image",
    "spiral-matrix",
    "set-matrix-zeroes",
    "jump-game",
    "partition-labels",
    "daily-temperatures",
    "decode-string",
    "minimum-path-sum",
    "unique-paths",
    "trapping-rain-water",
    "median-of-two-sorted-arrays",
    "minimum-window-substring",
    "largest-rectangle-in-histogram",
    "edit-distance",
    "sliding-window-maximum",
    "longest-valid-parentheses",
    "distinct-subsequences",
    "regular-expression-matching",
]


def add_fifty_one_problems(apps, schema_editor):
    Problem = apps.get_model("problems", "Problem")
    TestCase = apps.get_model("problems", "TestCase")
    Tag = apps.get_model("problems", "Tag")

    def get_tag(name):
        tag, _ = Tag.objects.get_or_create(name=name, defaults={"slug": slugify(name)})
        return tag

    problems_data = [
        {
            "title": "Valid Parentheses",
            "slug": "valid-parentheses",
            "description": "Given a string containing only brackets, return true if it is valid.",
            "constraints": "1 <= s.length <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "isValid",
            "signature_text": "def isValid(self, s: str) -> bool",
            "tags": ["Strings", "Stack"],
            "cases": [({"s": "()[]{}"}, True), ({"s": "(]"}, False)],
        },
        {
            "title": "Longest Common Prefix",
            "slug": "longest-common-prefix",
            "description": "Return the longest common prefix among all strings.",
            "constraints": "1 <= strs.length <= 200",
            "difficulty": 1,
            "entrypoint_name": "longestCommonPrefix",
            "signature_text": "def longestCommonPrefix(self, strs: list[str]) -> str",
            "tags": ["Strings"],
            "cases": [({"strs": ["flower", "flow", "flight"]}, "fl"), ({"strs": ["dog", "racecar", "car"]}, "")],
        },
        {
            "title": "Roman to Integer",
            "slug": "roman-to-integer",
            "description": "Convert a Roman numeral to an integer.",
            "constraints": "1 <= s.length <= 15",
            "difficulty": 1,
            "entrypoint_name": "romanToInt",
            "signature_text": "def romanToInt(self, s: str) -> int",
            "tags": ["Strings", "Hashing"],
            "cases": [({"s": "III"}, 3), ({"s": "MCMXCIV"}, 1994)],
        },
        {
            "title": "Palindrome Number",
            "slug": "palindrome-number",
            "description": "Return true if integer x is a palindrome.",
            "constraints": "-2^31 <= x <= 2^31-1",
            "difficulty": 1,
            "entrypoint_name": "isPalindrome",
            "signature_text": "def isPalindrome(self, x: int) -> bool",
            "tags": ["Math"],
            "cases": [({"x": 121}, True), ({"x": -121}, False)],
        },
        {
            "title": "Plus One",
            "slug": "plus-one",
            "description": "Given digits representing a non-negative integer, return the integer plus one.",
            "constraints": "1 <= digits.length <= 100",
            "difficulty": 1,
            "entrypoint_name": "plusOne",
            "signature_text": "def plusOne(self, digits: list[int]) -> list[int]",
            "tags": ["Arrays", "Math"],
            "cases": [({"digits": [1, 2, 3]}, [1, 2, 4]), ({"digits": [9, 9]}, [1, 0, 0])],
        },
        {
            "title": "Missing Number",
            "slug": "missing-number",
            "description": "Given distinct numbers in [0, n], return the missing number.",
            "constraints": "1 <= nums.length <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "missingNumber",
            "signature_text": "def missingNumber(self, nums: list[int]) -> int",
            "tags": ["Arrays", "Math"],
            "cases": [({"nums": [3, 0, 1]}, 2), ({"nums": [0, 1]}, 2)],
        },
        {
            "title": "Single Number",
            "slug": "single-number",
            "description": "Every element appears twice except one. Return that one.",
            "constraints": "1 <= nums.length <= 3*10^4",
            "difficulty": 1,
            "entrypoint_name": "singleNumber",
            "signature_text": "def singleNumber(self, nums: list[int]) -> int",
            "tags": ["Arrays", "Bit Manipulation"],
            "cases": [({"nums": [2, 2, 1]}, 1), ({"nums": [4, 1, 2, 1, 2]}, 4)],
        },
        {
            "title": "First Unique Character in a String",
            "slug": "first-unique-character-in-a-string",
            "description": "Return index of first non-repeating character, else -1.",
            "constraints": "1 <= s.length <= 10^5",
            "difficulty": 1,
            "entrypoint_name": "firstUniqChar",
            "signature_text": "def firstUniqChar(self, s: str) -> int",
            "tags": ["Strings", "Hashing"],
            "cases": [({"s": "leetcode"}, 0), ({"s": "aabb"}, -1)],
        },
        {
            "title": "Valid Mountain Array",
            "slug": "valid-mountain-array",
            "description": "Return true if arr strictly increases then strictly decreases.",
            "constraints": "1 <= arr.length <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "validMountainArray",
            "signature_text": "def validMountainArray(self, arr: list[int]) -> bool",
            "tags": ["Arrays", "Two Pointers"],
            "cases": [({"arr": [0, 3, 2, 1]}, True), ({"arr": [3, 5, 5]}, False)],
        },
        {
            "title": "Squares of a Sorted Array",
            "slug": "squares-of-a-sorted-array",
            "description": "Return sorted squares of each number.",
            "constraints": "1 <= nums.length <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "sortedSquares",
            "signature_text": "def sortedSquares(self, nums: list[int]) -> list[int]",
            "tags": ["Arrays", "Two Pointers"],
            "cases": [({"nums": [-4, -1, 0, 3, 10]}, [0, 1, 9, 16, 100]), ({"nums": [-7, -3, 2, 3, 11]}, [4, 9, 9, 49, 121])],
        },
        {
            "title": "Running Sum of 1D Array",
            "slug": "running-sum-of-1d-array",
            "description": "Return running sum of nums.",
            "constraints": "1 <= nums.length <= 1000",
            "difficulty": 1,
            "entrypoint_name": "runningSum",
            "signature_text": "def runningSum(self, nums: list[int]) -> list[int]",
            "tags": ["Arrays", "Prefix Sum"],
            "cases": [({"nums": [1, 2, 3, 4]}, [1, 3, 6, 10]), ({"nums": [3, 1, 2, 10, 1]}, [3, 4, 6, 16, 17])],
        },
        {
            "title": "Richest Customer Wealth",
            "slug": "richest-customer-wealth",
            "description": "Return max row sum in accounts matrix.",
            "constraints": "1 <= m, n <= 50",
            "difficulty": 1,
            "entrypoint_name": "maximumWealth",
            "signature_text": "def maximumWealth(self, accounts: list[list[int]]) -> int",
            "tags": ["Arrays", "Matrix"],
            "cases": [({"accounts": [[1, 2, 3], [3, 2, 1]]}, 6), ({"accounts": [[1, 5], [7, 3], [3, 5]]}, 10)],
        },
        {
            "title": "Number of 1 Bits",
            "slug": "number-of-1-bits",
            "description": "Return number of set bits in the binary representation of n.",
            "constraints": "0 <= n <= 2^32 - 1",
            "difficulty": 1,
            "entrypoint_name": "hammingWeight",
            "signature_text": "def hammingWeight(self, n: int) -> int",
            "tags": ["Bit Manipulation"],
            "cases": [({"n": 11}, 3), ({"n": 128}, 1)],
        },
        {
            "title": "Pascal's Triangle II",
            "slug": "pascals-triangle-ii",
            "description": "Return the rowIndex-th row of Pascal's triangle.",
            "constraints": "0 <= rowIndex <= 33",
            "difficulty": 1,
            "entrypoint_name": "getRow",
            "signature_text": "def getRow(self, rowIndex: int) -> list[int]",
            "tags": ["Arrays", "Dynamic Programming"],
            "cases": [({"rowIndex": 3}, [1, 3, 3, 1]), ({"rowIndex": 0}, [1])],
        },
        {
            "title": "Transpose Matrix",
            "slug": "transpose-matrix",
            "description": "Return the transpose of matrix.",
            "constraints": "1 <= rows, cols <= 100",
            "difficulty": 1,
            "entrypoint_name": "transpose",
            "signature_text": "def transpose(self, matrix: list[list[int]]) -> list[list[int]]",
            "tags": ["Matrix"],
            "cases": [({"matrix": [[1, 2, 3], [4, 5, 6]]}, [[1, 4], [2, 5], [3, 6]]), ({"matrix": [[1]]}, [[1]])],
        },
        {
            "title": "Find Pivot Index",
            "slug": "find-pivot-index",
            "description": "Return index where left sum equals right sum, else -1.",
            "constraints": "1 <= nums.length <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "pivotIndex",
            "signature_text": "def pivotIndex(self, nums: list[int]) -> int",
            "tags": ["Arrays", "Prefix Sum"],
            "cases": [({"nums": [1, 7, 3, 6, 5, 6]}, 3), ({"nums": [1, 2, 3]}, -1)],
        },
        {
            "title": "Intersection of Two Arrays",
            "slug": "intersection-of-two-arrays",
            "description": "Return unique intersection in sorted order.",
            "constraints": "1 <= nums1.length, nums2.length <= 1000",
            "difficulty": 1,
            "entrypoint_name": "intersection",
            "signature_text": "def intersection(self, nums1: list[int], nums2: list[int]) -> list[int]",
            "tags": ["Arrays", "Hashing"],
            "cases": [({"nums1": [1, 2, 2, 1], "nums2": [2, 2]}, [2]), ({"nums1": [4, 9, 5], "nums2": [9, 4, 9, 8, 4]}, [4, 9])],
        },
        {
            "title": "Fizz Buzz",
            "slug": "fizz-buzz",
            "description": "Return fizz buzz strings from 1 to n.",
            "constraints": "1 <= n <= 10^4",
            "difficulty": 1,
            "entrypoint_name": "fizzBuzz",
            "signature_text": "def fizzBuzz(self, n: int) -> list[str]",
            "tags": ["Math", "Simulation"],
            "cases": [({"n": 5}, ["1", "2", "Fizz", "4", "Buzz"]), ({"n": 3}, ["1", "2", "Fizz"])],
        },
        {
            "title": "Valid Sudoku",
            "slug": "valid-sudoku",
            "description": "Check if a partially filled sudoku board is valid.",
            "constraints": "board is 9x9",
            "difficulty": 2,
            "entrypoint_name": "isValidSudoku",
            "signature_text": "def isValidSudoku(self, board: list[list[str]]) -> bool",
            "tags": ["Matrix", "Hashing"],
            "cases": [
                ({"board": [["5","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]}, True),
                ({"board": [["8","3",".",".","7",".",".",".","."],["6",".",".","1","9","5",".",".","."],[".","9","8",".",".",".",".","6","."],["8",".",".",".","6",".",".",".","3"],["4",".",".","8",".","3",".",".","1"],["7",".",".",".","2",".",".",".","6"],[".","6",".",".",".",".","2","8","."],[".",".",".","4","1","9",".",".","5"],[".",".",".",".","8",".",".","7","9"]]}, False),
            ],
        },
        {
            "title": "Top K Frequent Elements",
            "slug": "top-k-frequent-elements",
            "description": "Return top k frequent numbers sorted ascending by value in ties.",
            "constraints": "1 <= nums.length <= 10^5",
            "difficulty": 2,
            "entrypoint_name": "topKFrequent",
            "signature_text": "def topKFrequent(self, nums: list[int], k: int) -> list[int]",
            "tags": ["Arrays", "Hashing", "Heap"],
            "cases": [({"nums": [1, 1, 1, 2, 2, 3], "k": 2}, [1, 2]), ({"nums": [4, 4, 6, 6, 6, 7], "k": 1}, [6])],
        },
        {
            "title": "Subarray Sum Equals K",
            "slug": "subarray-sum-equals-k",
            "description": "Count contiguous subarrays that sum to k.",
            "constraints": "1 <= nums.length <= 2*10^4",
            "difficulty": 2,
            "entrypoint_name": "subarraySum",
            "signature_text": "def subarraySum(self, nums: list[int], k: int) -> int",
            "tags": ["Arrays", "Prefix Sum", "Hashing"],
            "cases": [({"nums": [1, 1, 1], "k": 2}, 2), ({"nums": [1, 2, 3], "k": 3}, 2)],
        },
        {
            "title": "Longest Substring Without Repeating Characters",
            "slug": "longest-substring-without-repeating-characters",
            "description": "Return length of the longest substring without repeated characters.",
            "constraints": "0 <= s.length <= 5*10^4",
            "difficulty": 2,
            "entrypoint_name": "lengthOfLongestSubstring",
            "signature_text": "def lengthOfLongestSubstring(self, s: str) -> int",
            "tags": ["Strings", "Sliding Window"],
            "cases": [({"s": "abcabcbb"}, 3), ({"s": "bbbbb"}, 1)],
        },
        {
            "title": "Container With Most Water",
            "slug": "container-with-most-water",
            "description": "Given heights, return max area of water container.",
            "constraints": "2 <= height.length <= 10^5",
            "difficulty": 2,
            "entrypoint_name": "maxArea",
            "signature_text": "def maxArea(self, height: list[int]) -> int",
            "tags": ["Arrays", "Two Pointers"],
            "cases": [({"height": [1, 8, 6, 2, 5, 4, 8, 3, 7]}, 49), ({"height": [1, 1]}, 1)],
        },
        {
            "title": "Longest Palindromic Substring Length",
            "slug": "longest-palindromic-substring-length",
            "description": "Return the length of the longest palindromic substring.",
            "constraints": "1 <= s.length <= 1000",
            "difficulty": 2,
            "entrypoint_name": "longestPalindromeLength",
            "signature_text": "def longestPalindromeLength(self, s: str) -> int",
            "tags": ["Strings", "Dynamic Programming"],
            "cases": [({"s": "babad"}, 3), ({"s": "cbbd"}, 2)],
        },
        {
            "title": "Coin Change",
            "slug": "coin-change",
            "description": "Return fewest number of coins needed to make amount, else -1.",
            "constraints": "1 <= coins.length <= 12",
            "difficulty": 2,
            "entrypoint_name": "coinChange",
            "signature_text": "def coinChange(self, coins: list[int], amount: int) -> int",
            "tags": ["Dynamic Programming"],
            "cases": [({"coins": [1, 2, 5], "amount": 11}, 3), ({"coins": [2], "amount": 3}, -1)],
        },
        {
            "title": "House Robber II",
            "slug": "house-robber-ii",
            "description": "Houses are in a circle. Return max amount you can rob.",
            "constraints": "1 <= nums.length <= 100",
            "difficulty": 2,
            "entrypoint_name": "rob",
            "signature_text": "def rob(self, nums: list[int]) -> int",
            "tags": ["Dynamic Programming"],
            "cases": [({"nums": [2, 3, 2]}, 3), ({"nums": [1, 2, 3, 1]}, 4)],
        },
        {
            "title": "Number of Islands",
            "slug": "number-of-islands",
            "description": "Count connected components of '1' in a grid.",
            "constraints": "1 <= m, n <= 300",
            "difficulty": 2,
            "entrypoint_name": "numIslands",
            "signature_text": "def numIslands(self, grid: list[list[str]]) -> int",
            "tags": ["Graphs", "DFS", "BFS"],
            "cases": [({"grid": [["1", "1", "1", "1", "0"], ["1", "1", "0", "1", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "0", "0", "0"]]}, 1), ({"grid": [["1", "1", "0", "0", "0"], ["1", "1", "0", "0", "0"], ["0", "0", "1", "0", "0"], ["0", "0", "0", "1", "1"]]}, 3)],
        },
        {
            "title": "Course Schedule",
            "slug": "course-schedule",
            "description": "Return true if all courses can be finished.",
            "constraints": "1 <= numCourses <= 2000",
            "difficulty": 2,
            "entrypoint_name": "canFinish",
            "signature_text": "def canFinish(self, numCourses: int, prerequisites: list[list[int]]) -> bool",
            "tags": ["Graphs", "Topological Sort"],
            "cases": [({"numCourses": 2, "prerequisites": [[1, 0]]}, True), ({"numCourses": 2, "prerequisites": [[1, 0], [0, 1]]}, False)],
        },
        {
            "title": "Search in Rotated Sorted Array",
            "slug": "search-in-rotated-sorted-array",
            "description": "Return index of target in rotated sorted array, else -1.",
            "constraints": "1 <= nums.length <= 5000",
            "difficulty": 2,
            "entrypoint_name": "search",
            "signature_text": "def search(self, nums: list[int], target: int) -> int",
            "tags": ["Arrays", "Binary Search"],
            "cases": [({"nums": [4, 5, 6, 7, 0, 1, 2], "target": 0}, 4), ({"nums": [4, 5, 6, 7, 0, 1, 2], "target": 3}, -1)],
        },
        {
            "title": "Find Minimum in Rotated Sorted Array",
            "slug": "find-minimum-in-rotated-sorted-array",
            "description": "Return minimum element in rotated sorted array.",
            "constraints": "1 <= nums.length <= 5000",
            "difficulty": 2,
            "entrypoint_name": "findMin",
            "signature_text": "def findMin(self, nums: list[int]) -> int",
            "tags": ["Arrays", "Binary Search"],
            "cases": [({"nums": [3, 4, 5, 1, 2]}, 1), ({"nums": [11, 13, 15, 17]}, 11)],
        },
        {
            "title": "Target Sum Ways",
            "slug": "target-sum-ways",
            "description": "Assign + or - to each number. Return number of ways to reach target.",
            "constraints": "1 <= nums.length <= 20",
            "difficulty": 2,
            "entrypoint_name": "findTargetSumWays",
            "signature_text": "def findTargetSumWays(self, nums: list[int], target: int) -> int",
            "tags": ["Dynamic Programming", "Backtracking"],
            "cases": [({"nums": [1, 1, 1, 1, 1], "target": 3}, 5), ({"nums": [1], "target": 1}, 1)],
        },
        {
            "title": "Longest Consecutive Sequence",
            "slug": "longest-consecutive-sequence",
            "description": "Return length of the longest consecutive elements sequence.",
            "constraints": "0 <= nums.length <= 10^5",
            "difficulty": 2,
            "entrypoint_name": "longestConsecutive",
            "signature_text": "def longestConsecutive(self, nums: list[int]) -> int",
            "tags": ["Arrays", "Hashing"],
            "cases": [({"nums": [100, 4, 200, 1, 3, 2]}, 4), ({"nums": [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]}, 9)],
        },
        {
            "title": "Sort Colors",
            "slug": "sort-colors",
            "description": "Given array with 0,1,2, return sorted array.",
            "constraints": "1 <= nums.length <= 300",
            "difficulty": 2,
            "entrypoint_name": "sortColors",
            "signature_text": "def sortColors(self, nums: list[int]) -> list[int]",
            "tags": ["Arrays", "Two Pointers"],
            "cases": [({"nums": [2, 0, 2, 1, 1, 0]}, [0, 0, 1, 1, 2, 2]), ({"nums": [2, 0, 1]}, [0, 1, 2])],
        },
        {
            "title": "Rotate Image",
            "slug": "rotate-image",
            "description": "Return matrix rotated 90 degrees clockwise.",
            "constraints": "n == matrix.length",
            "difficulty": 2,
            "entrypoint_name": "rotate",
            "signature_text": "def rotate(self, matrix: list[list[int]]) -> list[list[int]]",
            "tags": ["Matrix"],
            "cases": [({"matrix": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}, [[7, 4, 1], [8, 5, 2], [9, 6, 3]]), ({"matrix": [[1, 2], [3, 4]]}, [[3, 1], [4, 2]])],
        },
        {
            "title": "Spiral Matrix",
            "slug": "spiral-matrix",
            "description": "Return all elements in spiral order.",
            "constraints": "1 <= m, n <= 10",
            "difficulty": 2,
            "entrypoint_name": "spiralOrder",
            "signature_text": "def spiralOrder(self, matrix: list[list[int]]) -> list[int]",
            "tags": ["Matrix", "Simulation"],
            "cases": [({"matrix": [[1, 2, 3], [4, 5, 6], [7, 8, 9]]}, [1, 2, 3, 6, 9, 8, 7, 4, 5]), ({"matrix": [[1, 2, 3, 4]]}, [1, 2, 3, 4])],
        },
        {
            "title": "Set Matrix Zeroes",
            "slug": "set-matrix-zeroes",
            "description": "If an element is zero, set its row and column to zero. Return final matrix.",
            "constraints": "1 <= m, n <= 200",
            "difficulty": 2,
            "entrypoint_name": "setZeroes",
            "signature_text": "def setZeroes(self, matrix: list[list[int]]) -> list[list[int]]",
            "tags": ["Matrix"],
            "cases": [({"matrix": [[1, 1, 1], [1, 0, 1], [1, 1, 1]]}, [[1, 0, 1], [0, 0, 0], [1, 0, 1]]), ({"matrix": [[0, 1]]}, [[0, 0]])],
        },
        {
            "title": "Jump Game",
            "slug": "jump-game",
            "description": "Return true if you can reach the last index.",
            "constraints": "1 <= nums.length <= 10^4",
            "difficulty": 2,
            "entrypoint_name": "canJump",
            "signature_text": "def canJump(self, nums: list[int]) -> bool",
            "tags": ["Arrays", "Greedy"],
            "cases": [({"nums": [2, 3, 1, 1, 4]}, True), ({"nums": [3, 2, 1, 0, 4]}, False)],
        },
        {
            "title": "Partition Labels",
            "slug": "partition-labels",
            "description": "Partition string so each letter appears in at most one part; return part lengths.",
            "constraints": "1 <= s.length <= 500",
            "difficulty": 2,
            "entrypoint_name": "partitionLabels",
            "signature_text": "def partitionLabels(self, s: str) -> list[int]",
            "tags": ["Strings", "Greedy"],
            "cases": [({"s": "ababcbacadefegdehijhklij"}, [9, 7, 8]), ({"s": "eccbbbbdec"}, [10])],
        },
        {
            "title": "Daily Temperatures",
            "slug": "daily-temperatures",
            "description": "Return days to wait until a warmer temperature.",
            "constraints": "1 <= temperatures.length <= 10^5",
            "difficulty": 2,
            "entrypoint_name": "dailyTemperatures",
            "signature_text": "def dailyTemperatures(self, temperatures: list[int]) -> list[int]",
            "tags": ["Arrays", "Stack", "Monotonic Stack"],
            "cases": [({"temperatures": [73, 74, 75, 71, 69, 72, 76, 73]}, [1, 1, 4, 2, 1, 1, 0, 0]), ({"temperatures": [30, 40, 50, 60]}, [1, 1, 1, 0])],
        },
        {
            "title": "Decode String",
            "slug": "decode-string",
            "description": "Decode strings encoded as k[encoded_string].",
            "constraints": "1 <= s.length <= 30",
            "difficulty": 2,
            "entrypoint_name": "decodeString",
            "signature_text": "def decodeString(self, s: str) -> str",
            "tags": ["Strings", "Stack"],
            "cases": [({"s": "3[a]2[bc]"}, "aaabcbc"), ({"s": "3[a2[c]]"}, "accaccacc")],
        },
        {
            "title": "Minimum Path Sum",
            "slug": "minimum-path-sum",
            "description": "Move only right or down; return min path sum to bottom-right.",
            "constraints": "1 <= m, n <= 200",
            "difficulty": 2,
            "entrypoint_name": "minPathSum",
            "signature_text": "def minPathSum(self, grid: list[list[int]]) -> int",
            "tags": ["Dynamic Programming", "Matrix"],
            "cases": [({"grid": [[1, 3, 1], [1, 5, 1], [4, 2, 1]]}, 7), ({"grid": [[1, 2, 3], [4, 5, 6]]}, 12)],
        },
        {
            "title": "Unique Paths",
            "slug": "unique-paths",
            "description": "Return number of unique paths in m x n grid moving right/down.",
            "constraints": "1 <= m, n <= 100",
            "difficulty": 2,
            "entrypoint_name": "uniquePaths",
            "signature_text": "def uniquePaths(self, m: int, n: int) -> int",
            "tags": ["Dynamic Programming", "Combinatorics"],
            "cases": [({"m": 3, "n": 7}, 28), ({"m": 3, "n": 2}, 3)],
        },
        {
            "title": "Trapping Rain Water",
            "slug": "trapping-rain-water",
            "description": "Return amount of trapped rain water.",
            "constraints": "1 <= height.length <= 2*10^4",
            "difficulty": 3,
            "entrypoint_name": "trap",
            "signature_text": "def trap(self, height: list[int]) -> int",
            "tags": ["Arrays", "Two Pointers", "Stack"],
            "cases": [({"height": [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]}, 6), ({"height": [4, 2, 0, 3, 2, 5]}, 9)],
        },
        {
            "title": "Median of Two Sorted Arrays",
            "slug": "median-of-two-sorted-arrays",
            "description": "Return median of two sorted arrays.",
            "constraints": "0 <= m, n <= 1000",
            "difficulty": 3,
            "entrypoint_name": "findMedianSortedArrays",
            "signature_text": "def findMedianSortedArrays(self, nums1: list[int], nums2: list[int]) -> float",
            "tags": ["Arrays", "Binary Search"],
            "cases": [({"nums1": [1, 3], "nums2": [2]}, 2.0), ({"nums1": [1, 2], "nums2": [3, 4]}, 2.5)],
        },
        {
            "title": "Minimum Window Substring",
            "slug": "minimum-window-substring",
            "description": "Return the minimum window in s that contains all chars of t.",
            "constraints": "1 <= s.length, t.length <= 10^5",
            "difficulty": 3,
            "entrypoint_name": "minWindow",
            "signature_text": "def minWindow(self, s: str, t: str) -> str",
            "tags": ["Strings", "Sliding Window"],
            "cases": [({"s": "ADOBECODEBANC", "t": "ABC"}, "BANC"), ({"s": "a", "t": "aa"}, "")],
        },
        {
            "title": "Largest Rectangle in Histogram",
            "slug": "largest-rectangle-in-histogram",
            "description": "Return area of largest rectangle in histogram.",
            "constraints": "1 <= heights.length <= 10^5",
            "difficulty": 3,
            "entrypoint_name": "largestRectangleArea",
            "signature_text": "def largestRectangleArea(self, heights: list[int]) -> int",
            "tags": ["Stack", "Monotonic Stack"],
            "cases": [({"heights": [2, 1, 5, 6, 2, 3]}, 10), ({"heights": [2, 4]}, 4)],
        },
        {
            "title": "Edit Distance",
            "slug": "edit-distance",
            "description": "Return minimum number of operations to convert word1 to word2.",
            "constraints": "0 <= word1.length, word2.length <= 500",
            "difficulty": 3,
            "entrypoint_name": "minDistance",
            "signature_text": "def minDistance(self, word1: str, word2: str) -> int",
            "tags": ["Dynamic Programming", "Strings"],
            "cases": [({"word1": "horse", "word2": "ros"}, 3), ({"word1": "intention", "word2": "execution"}, 5)],
        },
        {
            "title": "Sliding Window Maximum",
            "slug": "sliding-window-maximum",
            "description": "Return max value in each sliding window of size k.",
            "constraints": "1 <= nums.length <= 10^5",
            "difficulty": 3,
            "entrypoint_name": "maxSlidingWindow",
            "signature_text": "def maxSlidingWindow(self, nums: list[int], k: int) -> list[int]",
            "tags": ["Arrays", "Deque", "Sliding Window"],
            "cases": [({"nums": [1, 3, -1, -3, 5, 3, 6, 7], "k": 3}, [3, 3, 5, 5, 6, 7]), ({"nums": [1], "k": 1}, [1])],
        },
        {
            "title": "Longest Valid Parentheses",
            "slug": "longest-valid-parentheses",
            "description": "Return length of longest valid parentheses substring.",
            "constraints": "0 <= s.length <= 3*10^4",
            "difficulty": 3,
            "entrypoint_name": "longestValidParentheses",
            "signature_text": "def longestValidParentheses(self, s: str) -> int",
            "tags": ["Strings", "Stack", "Dynamic Programming"],
            "cases": [({"s": "(()"}, 2), ({"s": ")()())"}, 4)],
        },
        {
            "title": "Distinct Subsequences",
            "slug": "distinct-subsequences",
            "description": "Return number of distinct subsequences of s that equal t.",
            "constraints": "1 <= s.length, t.length <= 1000",
            "difficulty": 3,
            "entrypoint_name": "numDistinct",
            "signature_text": "def numDistinct(self, s: str, t: str) -> int",
            "tags": ["Dynamic Programming", "Strings"],
            "cases": [({"s": "rabbbit", "t": "rabbit"}, 3), ({"s": "babgbag", "t": "bag"}, 5)],
        },
        {
            "title": "Regular Expression Matching",
            "slug": "regular-expression-matching",
            "description": "Implement regex matching with support for '.' and '*'.",
            "constraints": "1 <= s.length <= 20",
            "difficulty": 3,
            "entrypoint_name": "isMatch",
            "signature_text": "def isMatch(self, s: str, p: str) -> bool",
            "tags": ["Dynamic Programming", "Strings"],
            "cases": [({"s": "aa", "p": "a"}, False), ({"s": "aab", "p": "c*a*b"}, True)],
        },
    ]

    for pdata in problems_data:
        if Problem.objects.filter(slug=pdata["slug"]).exists():
            continue

        starter_code = (
            "class Solution:\n"
            f"    {pdata['signature_text'].replace('def ', 'def ', 1)}:\n"
            "        pass"
        )

        problem = Problem.objects.create(
            title=pdata["title"],
            slug=pdata["slug"],
            description=pdata["description"],
            constraints=pdata.get("constraints", ""),
            follow_up=pdata.get("follow_up", ""),
            difficulty=pdata["difficulty"],
            judge_mode="function",
            entrypoint_type="class",
            entrypoint_name=pdata["entrypoint_name"],
            signature_text=pdata["signature_text"],
            starter_code=starter_code,
            is_published=True,
        )

        for tag_name in pdata.get("tags", []):
            problem.tags.add(get_tag(tag_name))

        for index, (args, expected) in enumerate(pdata.get("cases", [])):
            input_json = json.dumps(args)
            output_json = json.dumps(expected)
            TestCase.objects.create(
                problem=problem,
                input_data=input_json,
                expected_output=output_json,
                display_input=input_json,
                display_output=output_json,
                is_sample=index == 0,
            )


def remove_fifty_one_problems(apps, schema_editor):
    Problem = apps.get_model("problems", "Problem")
    Problem.objects.filter(slug__in=PROBLEM_SLUGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0014_add_more_seed_problems"),
    ]

    operations = [
        migrations.RunPython(add_fifty_one_problems, remove_fifty_one_problems),
    ]
