# Generated by Django 6.0.1 on 2026-01-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of what this course covers')),
                ('is_published', models.BooleanField(default=False, help_text='Only published courses are visible to learners')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the courses list (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('summary', models.CharField(blank=True, help_text='Short description shown in lesson lists', max_length=500)),
                ('content_markdown', models.TextField(help_text='Lesson content in Markdown format. Supports headings, lists, code blocks, links, etc.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the course (lower = first)')),
                ('is_published', models.BooleanField(default=False, help_text='Only published lessons are visible to learners')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Optional: assign to a course for organized learning paths', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lessons.course')),
                ('problems', models.ManyToManyField(blank=True, help_text='Problems related to this lesson for practice', related_name='lessons', to='problems.problem')),
            ],
            options={
                'ordering': ['course', 'order', 'title'],
            },
        ),
    ]
